apiVersion: v2
name: chatwoot-helm
description: A Helm chart for deploying Chatwoot on Kubernetes.
type: Application
keywords:
  - chatwoot
  - open source
  - helm
  - kubernetes

type: application

version: 0.1.0

appVersion: "1.16.0"
