apiVersion: v2
dependencies:
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 10.5.3
  - condition: redis.enabled
    name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 14.7.2
name: chatwoot-helm
description: A Helm chart for deploying Chatwoot on Kubernetes.
type: Application
keywords:
  - chatwoot
  - open source
  - helm
  - kubernetes

type: application

version: 0.3.0

appVersion: "1.16.0"
