# Default values for chatwoot
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# Overrides the image tag whose default is the chart appVersion.
image:
  repository: registry.digitalocean.com/nexmeter-registry/omnipurchase
  tag: latest
  pullPolicy: Always

imagePullSecrets:
  - name: registry-nexmeter-registry 

# Set to autoscaling/v2beta2 for older versions of kubernetes that do not have autoscaling/v2 API (pre v1.26)
# See https://kubernetes.io/docs/reference/using-api/deprecation-guide/#horizontalpodautoscaler-v126
autoscaling:
  apiVersion: autoscaling/v2

web:
  hpa:
     # set this to true to enable horizontal pod autoscaling
     # uncomment values.resources section if hpa is enabled
    enabled: false
    cputhreshold: 75
    minpods: 1
    maxpods: 10
  replicaCount: 1
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 500m
    #   memory: 512Mi
    # requests:
    #   cpu: 250m
    #   memory: 256Mi
worker:
  hpa:
    # set this to true to enable horizontal pod autoscaling
    # uncomment values.resources section if hpa is enabled
    enabled: false
    cputhreshold: 75
    minpods: 2
    maxpods: 10
  replicaCount: 2
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 500m
    #   memory: 512Mi
    # requests:
    #   cpu: 250m
    #   memory: 256Mi

services:
  name: chatwoot
  internalPort: 3000
  targetPort: 3000
  type: ClusterIP
  annotations: {}

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
  hosts:
    - host: omnipurchase.dev.omnifylabs.com
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: chatwoot
              port:
                number: 3000

nodeSelector: {}

tolerations: []

affinity: {}

postgresql:
  enabled: false
  # nameOverride: chatwoot-postgresql
  auth:
    username: postgres-username
    postgresPassword: postgres-password
    database: defaultdb
    # when existingSecret is defined auth.password, auth.PostgressPassword
    # is ignored.
    # existingSecret: secret-name
    # secretKeys:
    #   adminPasswordKey: postgres-password
    #   replicationPasswordKey: replication-password
  # The following variables are only used when internal PG is disabled
  postgresqlHost: private-db-postgresql-sfo3-39184-do-user-15526827-0.f.db.ondigitalocean.com
  postgresqlPort: 25060
  sslmode: require

redis:
  enabled: false
  auth:
    # username: default
    # password:
    # when defined the password field is ignored
    existingSecret: null
    # existingSecretPasswordKey: 
  # The following variables are only used when internal Redis is disabled
  host: private-db-caching-sfo3-20344-do-user-15526827-0.f.db.ondigitalocean.com
  # Just omit the password field if your redis cluster doesn't use password
  password: redis-password
  port: 25061

# Provide affinity for hooks if needed
hooks:
  affinity: {}
  migrate:
    env: []
    resources:
      limits:
        memory: 1000Mi
      requests:
        memory: 1000Mi
    # Defaults to performing the DB migration job after the install/upgrade.
    # Can be overridden to "pre-install,pre-upgrade" with caution to perform migrations that are sometimes required for the deployment to become healthy
    hookAnnotation: "post-install,post-upgrade"

# ENVIRONMENT VARIABLES

# If set, will apply environment variables found in this secret, after the variables defined in the env key.
existingEnvSecret: ""

env:
  ACTIVE_STORAGE_SERVICE: local
  ANDROID_BUNDLE_ID: com.chatwoot.app
  ANDROID_SHA256_CERT_FINGERPRINT: "AC:73:8E:DE:EB:56:EA:CC:10:87:02:A7:65:37:7B:38:D4:5D:D4:53:F8:3B:FB:D3:C6:28:64:1D:AA:08:1E:D8"
  ASSET_CDN_HOST: ""
  AWS_ACCESS_KEY_ID: ""
  AWS_REGION: ""
  AWS_SECRET_ACCESS_KEY: ""
  ENABLE_ACCOUNT_SIGNUP: false
  FB_APP_ID: ""
  FB_APP_SECRET: ""
  FB_VERIFY_TOKEN: ""
  FORCE_SSL: false
  FRONTEND_URL: "http://0.0.0.0:3000"
  INSTALLATION_ENV: helm
  IOS_APP_ID: 6C953F3RX2.com.chatwoot.app
  LOG_LEVEL: info
  LOG_SIZE: 500
  MAILER_INBOUND_EMAIL_DOMAIN: ""
  MAILER_SENDER_EMAIL: ""
  MAILGUN_INGRESS_SIGNING_KEY: ""
  MANDRILL_INGRESS_API_KEY: ""
  RAILS_ENV: production
  RAILS_INBOUND_EMAIL_PASSWORD: ""
  RAILS_INBOUND_EMAIL_SERVICE: ""
  RAILS_LOG_TO_STDOUT: true
  RAILS_MAX_THREADS: 5
  REDIS_SENTINEL_MASTER_NAME: ""
  REDIS_SENTINELS: ""
  REDIS_TLS: false
  S3_BUCKET_NAME: ""
  SECRET_KEY_BASE: replace_with_your_super_duper_secret_key_base
  SENTRY_DSN: ""
  SLACK_CLIENT_ID: ""
  SLACK_CLIENT_SECRET: ""
  SMTP_ADDRESS: ""
  SMTP_AUTHENTICATION: plain
  SMTP_ENABLE_STARTTLS_AUTO: true
  SMTP_OPENSSL_VERIFY_MODE: none
  SMTP_PASSWORD: ""
  SMTP_PORT: 587
  SMTP_USERNAME: ""
  TWITTER_APP_ID: ""
  TWITTER_CONSUMER_KEY: ""
  TWITTER_CONSUMER_SECRET: ""
  TWITTER_ENVIRONMENT: ""
  USE_INBOX_AVATAR_FOR_BOT: true
