web:
  hpa:
    enabled: true
    cputhreshold: 80
    minpods: 1
    maxpods: 10
  replicaCount: 1
worker:
  hpa:
    cputhreshold: 80
    minpods: 1
    maxpods: 10
    enabled: true
  replicaCount: 1

redis:
  architecture: standalone
  # replica:
  #   replicaCount: 1

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
