{{- if .Values.volumes.postgres.local }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.applicationArch.storage.db.name }}
  creationTimestamp: null
  labels:
    {{- include "postgres.labels" . | nindent 4}}
spec:
  ports:
    - name: {{ .Values.services.postgres.name | quote}}
      port: {{ int .Values.services.postgres.port }}
      targetPort: {{ int .Values.services.postgres.targetPort }}
  selector:
    {{- include "postgres.labels" . | nindent 4}}
status:
  loadBalancer: {}
{{- end }}