apiVersion: v1
kind: Service
metadata:
  name: {{ template "chatwoot.fullname" . }}
  creationTimestamp: null
  labels:
    {{- include "rails.labels" . | nindent 4}}

spec:
  ports:
    - name: {{ .Values.services.name | quote}}
      port: {{ int .Values.services.internlPort }}
      targetPort: {{ int .Values.services.targetPort }}
  type: {{ .Values.services.type }}
  selector:
    {{- include "rails.labels" . | nindent 4}}
status:
  loadBalancer: {}
