apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "chatwoot.fullname" . }}-web
  creationTimestamp: null
  labels:
    {{- include "rails.labels" . | nindent 4}}
spec:
  replicas: {{ int .Values.deployment.image.dockerHub.chatwoot.replicaCount }}
  selector:
    matchLabels:
      {{- include "rails.labels" . | nindent 6 }}
  strategy: {}
  template:
    metadata:

      creationTimestamp: null
      labels:
        {{- include "rails.labels" . | nindent 8 }}
    spec:
      containers:
        - args: 
            - bundle
            - exec
            - rails
            - s
            - -p
            - {{ .Values.deployment.image.dockerHub.chatwoot.port | quote}}
            - -b
            - 0.0.0.0
            
          command:
            - docker/entrypoints/rails.sh
          env:
            {{- include "chatwoot.environ" .  }}
          image: "{{ .Values.deployment.image.dockerHub.chatwoot.owner }}/{{ .Values.deployment.image.dockerHub.chatwoot.repository }}:{{ .Values.deployment.image.dockerHub.chatwoot.tag }}"
          name: {{ .Chart.Name }}-web
          ports:
            - containerPort: {{ int .Values.deployment.image.dockerHub.chatwoot.port }}
          imagePullPolicy: {{ .Values.deployment.image.imagePullPolicy }}
          resources: {}

status: {}
