apiVersion: v1
kind: Service
metadata:
  name: {{ template "chatwoot.fullname" . }}
  creationTimestamp: null
  labels:
    {{- include "rails.labels" . | nindent 4}}

spec:
  ports:
    - name: {{ .Values.services.rails.name | quote}}
      port: {{ int .Values.services.rails.port }}
      targetPort: {{ int .Values.services.rails.targetPort }}
  type: {{ .Values.services.rails.type }}
  selector:
    {{- include "rails.labels" . | nindent 4}}
status:
  loadBalancer: {}
