apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    {{- include "sidekiq.labels" . | nindent 4 }}
  name: {{ template "chatwoot.fullname" . }}-worker
spec:
  replicas: {{ int .Values.worker.replica }}
  selector:
    matchLabels:
      {{- include "sidekiq.labels" . | nindent 6 }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        {{- include "sidekiq.labels" . | nindent 8 }}
    spec:
      containers:
        - args:
            - bundle
            - exec
            - sidekiq
            - -C
            - config/sidekiq.yml
          env:
            {{- include "chatwoot.environ" .  }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          name: {{ .Chart.Name }}-workers
          resources: {}
          imagePullPolicy: {{ .Values.image.pullPolicy }}

status: {}
